# syntax=docker/dockerfile:1
FROM ubuntu:20.04

LABEL org.opencontainers.image.source=https://github.com/mzdun/movies-ws
LABEL org.opencontainers.image.description="Movies WebSocket image"
LABEL org.opencontainers.image.licenses=MIT

RUN apt-get update -y && \
    apt-get install -y software-properties-common && \
    add-apt-repository ppa:ubuntu-toolchain-r/test -y && \
    apt-get install -y libcap-dev libstdc++-11-dev

COPY @TAR_GZ_PACKAGE_FILE_NAME@ /tmp
RUN mkdir -p /app && \
    tar -xf /tmp/@TAR_GZ_PACKAGE_FILE_NAME@ --strip-components=1 -C /app
RUN rm /tmp/@TAR_GZ_PACKAGE_FILE_NAME@

ENV PATH=/app/bin:$PATH
ENV REPO_NAME=default
ENV REPO_PORT=9000
VOLUME /data
EXPOSE ${REPO_PORT}
ENTRYPOINT ["docker-start"]
