name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CONAN_REVISIONS_ENABLED: 1

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        include:
            # Ubuntu ANY
          - os: ubuntu-latest
            ubuntu: true
            home: /home/runner
            latest_conan_hash: 2201c342a28c9c0629f72b66d12427fcb3dfa79412e47a41167d1e80c5b724c6
            # Windows ANY
          - os: windows-latest
            windows: true
            home: C:/Users/runneradmin
            latest_conan_hash: f818b75116ee4a3e3f30114d81f7091e6c9713c83ad849d59f0b15a04e373ece
            # Ubuntu Release
          - os: ubuntu-latest
            build_type: Release
            conan_profile: release
            cpack_generator: TGZ
            # Windows Release
          - os: windows-latest
            build_type: Release
            conan_profile: release
            cpack_generator: ZIP

    env:
      BUILD_TYPE: ${{ matrix.build_type }}

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
         submodules: true

    - name: Conanfile hash
      run: |
        echo ${{ hashFiles('conanfile.txt') }}
        echo ${{ matrix.latest_conan_hash }}
    - name: GCC 11
      if: ${{ matrix.ubuntu }}
      run: |
        sudo apt install g++-11 -y
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 90
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 90
        sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-11 90 
    - name: Conan output
      run: |
        import os
        dirname = os.path.join('build', 'conan')
        os.makedirs(dirname, exist_ok=True)
        print('>>>', os.getcwd(), '::', dirname, '::', os.path.isdir(dirname))
      shell: python

    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main

    - name: Configure Conan
      run: |
        conan profile new release --detect
        conan profile new debug --detect
        conan profile update settings.build_type=Release release
        conan profile update settings.build_type=Debug debug
        conan remote add mbits-conan https://mbits.jfrog.io/artifactory/api/conan/mbits-conan
        conan user -p ${{ secrets.JFROG_KEY }} -r mbits-conan ${{ secrets.JFROG_USER }}
    - name: Configure Conan (GCC C++11 library)
      if: ${{ matrix.ubuntu }}
      run: |
        conan profile update settings.compiler.libcxx=libstdc++11 release
        conan profile update settings.compiler.libcxx=libstdc++11 debug
    - name: Configure Conan (MSVC/MD)
      if: ${{ matrix.windows }}
      run: |
        conan profile update settings.compiler.runtime=MD release
        conan profile update settings.compiler.runtime=MDd debug

    - name: Conan cache
      uses: actions/cache@v3
      id: cache
      with:
        path: ${{ matrix.home }}/.conan/data
        key: ${{ matrix.os }}-${{ matrix.build_type }}-${{ hashFiles('conanfile.txt') }}
        restore-keys: |
          ${{ matrix.os }}-${{ matrix.build_type }}-${{ matrix.latest_conan_hash }}

    - name: Get Conan packages
      working-directory: ${{github.workspace}}/build/conan
      run: conan install ../.. --build missing -pr:b=${{matrix.conan_profile}} -pr:h=${{matrix.conan_profile}}

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Pack
      if: ${{ matrix.cpack_generator != '' }}
      working-directory: ${{github.workspace}}/build
      run: cpack -G ${{ matrix.cpack_generator }}

    - name: Upload packages
      uses: actions/upload-artifact@v3
      if: ${{ matrix.cpack_generator != '' }}
      with:
        name: Packages
        path: ${{github.workspace}}/build/packages/cov-*
