name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CONAN_REVISIONS_ENABLED: 1

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest] # , windows-latest]
        build_type: [Release]
        include:
            # Ubuntu ANY
          - os: ubuntu-latest
            ubuntu: true
            home: /home/runner
            latest_conan_hash: 591cf06f8ba3177ad697a3c24f523d14b4854a2458461c9619160400f5a27668
            # Windows ANY
          - os: windows-latest
            windows: true
            home: C:/Users/runneradmin
            latest_conan_hash: ae08c38291042d33cd9bea0e8e0cb180e208cc5cdcad249a6828cecc608ee20a
            # Ubuntu Release
          - os: ubuntu-latest
            build_type: Release
            cmake_profile: release-make
            cpack_generator: TGZ
            # Windows Release
          - os: windows-latest
            build_type: Release
            cmake_profile: release-vs22
            cpack_generator: ZIP
            # ANY Release
          - build_type: Release
            conan_profile: default
            cmake_build_profile: release
        exclude:
          - os: windows-latest

    env:
      BUILD_TYPE: ${{ matrix.build_type }}

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
         submodules: true

    - name: Conanfile hash
      run: |
        echo ${{ hashFiles('conanfile.txt') }}
        echo ${{ matrix.latest_conan_hash }}
    - name: GCC 11
      if: ${{ matrix.ubuntu }}
      run: |
        sudo apt install g++-11 libcap-dev -y
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 90
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 90
        sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-11 90 
    - name: Conan output
      run: |
        import os
        dirname = os.path.join('build', 'conan')
        os.makedirs(dirname, exist_ok=True)
        print('>>>', os.getcwd(), '::', dirname, '::', os.path.isdir(dirname))
      shell: python

    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main

    - name: Configure Conan
      run: |
        conan profile new default --detect
        conan remote add mbits-conan https://mbits.jfrog.io/artifactory/api/conan/mbits-conan
        conan user -p ${{ secrets.JFROG_KEY }} -r mbits-conan ${{ secrets.JFROG_USER }}
    - name: Configure Conan (GCC C++11 library)
      if: ${{ matrix.ubuntu }}
      run: |
        conan profile update settings.compiler.libcxx=libstdc++11 default
    - name: Configure Conan (MSVC/MD)
      if: ${{ matrix.windows }}
      run: |
        conan profile update settings.compiler.runtime=MD default

    - name: Conan cache
      uses: actions/cache@v3
      id: cache
      with:
        path: ${{ matrix.home }}/.conan/data
        key: ${{ matrix.os }}-${{ matrix.build_type }}-${{ hashFiles('conanfile.txt') }}
        restore-keys: |
          ${{ matrix.os }}-${{ matrix.build_type }}-${{ matrix.latest_conan_hash }}

    - name: Get Conan packages
      working-directory: ${{github.workspace}}/build/conan
      run: conan install ../.. --build missing -pr:b=${{matrix.conan_profile}} -pr:h=${{matrix.conan_profile}}

    - name: Configure CMake
      run: cmake --preset ${{matrix.cmake_profile}}

    - name: Build
      run: cmake --build --preset ${{matrix.cmake_build_profile}} --parallel

    - name: Pack
      if: ${{ matrix.cpack_generator != '' }}
      working-directory: ${{github.workspace}}/build/${{matrix.cmake_build_profile}}
      run: cpack -G ${{ matrix.cpack_generator }} -C ${{ matrix.build_type }}

    - name: Upload packages
      uses: actions/upload-artifact@v3
      if: ${{ matrix.cpack_generator != '' }}
      with:
        name: Packages
        path: ${{github.workspace}}/build/packages/movies-*
